Functions to read and write serialized files using protobuf.
AsherGlick/Burrito pull request #108
Opened 2022-12-06 02:05 UTC by klingbolt

Addressing issue #74

2022-12-08 04:58 UTC, AsherGlick requested changes

2022-12-08 23:46 UTC, klingbolt commented on xml_converter/src/icon_gen.cpp
> +    }
Understood. Making the change based on your solution.

2022-12-08 23:47 UTC, klingbolt commented on xml_converter/src/icon_gen.hpp
> +    bool set_trigger = false;
Because of the change to allocating trigger, this variable is removed.

2022-12-08 23:50 UTC, klingbolt commented on xml_converter/src/parseable.hpp
> +    virtual waypoint::Category as_protobuf(waypoint::Category proto_Category) const;
Understood. My solution felt clunky

2022-12-09 03:18 UTC, klingbolt commented on xml_converter/proto/waypoint.proto
> +    string type = 7;
I got names mixed up `type` is the xml name for `name`

2022-12-10 18:25 UTC, klingbolt commented on xml_converter/src/attribute/color.hpp
> +}
No. I did a couple variations and the only one accepted by clang-format and cpplint was what was submitted.

2022-12-10 18:26 UTC, klingbolt commented on xml_converter/src/attribute/festival_filter_gen.hpp
> +}
See comment on color.hpp

2022-12-10 18:26 UTC, klingbolt commented on xml_converter/src/attribute/image.hpp
> +}
Ignoring, See comment on color.hpp

2022-12-10 18:28 UTC, klingbolt commented on xml_converter/src/attribute/profession_filter_gen.hpp
> +}
One line. See comment on color.hpp

2022-12-10 18:30 UTC, klingbolt commented on xml_converter/src/attribute/specialization_filter_gen.hpp
> +}
Multi. See comment on color.hpp

2022-12-10 18:30 UTC, klingbolt commented on xml_converter/src/attribute/species_filter_gen.hpp
> +}
See comment on color.hpp

2022-12-10 18:31 UTC, klingbolt commented on xml_converter/src/attribute/trail_data.hpp
> +}
Linters say no. See comment on color.hpp

2022-12-10 18:31 UTC, klingbolt commented on xml_converter/src/attribute/unique_id.hpp
> +}
See comment on color.hpp
Indented wont work either 

`src/attribute/color.hpp:10:  Do not indent within a namespace  [runtime/indentation_namespace] [4]`

2022-12-10 18:37 UTC, klingbolt commented on xml_converter/src/xml_converter.cpp
> +    outfile.open(proto_filepath, ios::out | ios_base::binary);
I'm changing it to `ios::binary' for consistancy but it appears that even with `ios::` both out and binary are calling from `std::ios_base::openmode`

2022-12-10 18:38 UTC, klingbolt commented on xml_converter/src/xml_converter.cpp
> +    infile.open(proto_filepath, ios::in | ios_base::binary);
See comment above

2022-12-10 18:39 UTC, klingbolt commented on xml_converter/src/xml_converter.cpp
> +        cout << "Error in test_proto" << endl;
Added throw error

2022-12-10 18:40 UTC, klingbolt commented on xml_converter/src/xml_converter.cpp
> +    for (const auto& entry : filesystem::directory_iterator("../packs")) {
I was running inside `xml_convertor` inside the build instead of using `./build/xml_convertor` This has been reverted

2022-12-10 18:40 UTC, klingbolt commented on xml_converter/src/xml_converter.cpp
> +    write_xml_file("../export_packs/export.xml", &marker_categories, &parsed_pois);
See above

2022-12-10 19:26 UTC, klingbolt commented on xml_converter/src/attribute/reset_behavior_gen.cpp
> +    if (attribute_value == ResetBehavior::always_visible) {
Good idea. Adding case statements

2022-12-10 19:26 UTC, klingbolt commented on xml_converter/src/attribute/reset_behavior_gen.cpp
> +    }
Found the offending line that was causing duplicates and removed

2022-12-10 21:10 UTC, AsherGlick requested changes

2022-12-10 21:10 UTC, AsherGlick commented on xml_converter/src/icon_gen.cpp
> +waypoint::Waypoint Icon::as_protobuf() const {
This should probably return a `waypoint::Icon` see previous comment on similar changes.

2022-12-11 17:29 UTC, AsherGlick approved these changes

2022-12-11 17:29 UTC, merged