[SOTO Update] Shifted the burrito button to the right
AsherGlick/Burrito pull request #156
Opened 2023-08-25 00:24 UTC by klingbolt

Adjusted the button to account for the new icon

2023-08-25 01:07 UTC, AsherGlick commented
Cant seem to click the burrito icon anymore

2023-08-25 02:14 UTC, AsherGlick commented on Spatial.tscn
> +margin_top = 4.0
You took this off of the texture, now it does not line up to the top of the screen.
![Screenshot from 2023-08-24 21-12-58](https://github.com/AsherGlick/Burrito/assets/603989/7527bd8f-90e7-49e5-9f75-0e25c0a507dc)

2023-08-25 02:15 UTC, AsherGlick requested changes
You took this off of the texture, now it does not line up to the top of the screen.

2023-08-25 04:40 UTC, klingbolt commented on Spatial.gd
> +	var bottom_corner = menu_button.get_position() + menu_button.get_size()
By changing the values here to the properties the numbers come from, any more changes to the icons will be updated in the passthrough

2023-08-25 04:41 UTC, klingbolt commented on Spatial.tscn
>  margin_left = 32.0
I found that the margin besides the left margin does not make a difference if the margin is less than the size. Thus, removing the unnecessary ones

2023-08-28 23:58 UTC, AsherGlick commented
![Screenshot from 2023-08-28 18-55-11](https://github.com/AsherGlick/Burrito/assets/603989/dbf66328-367f-4f89-ac34-ba5c9bdef04a)
I think the icon is off still horizontally. My measurements say the icons are 32px apart

2023-08-29 00:01 UTC, AsherGlick commented
![Screenshot from 2023-08-28 18-59-33](https://github.com/AsherGlick/Burrito/assets/603989/b2ef7217-bb42-42f1-a5de-0e9ad04d06a3)
Looks like the height is still 1px off

2023-09-19 23:36 UTC, klingbolt commented on Spatial.tscn
>  [node name="EditorQuckPanel" type="PanelContainer" parent="Control/GlobalMenuButton"]
```suggestion
[node name="EditorQuckPanel" type="PanelContainer" parent="Control/GlobalMenuButton"]
visible = false
```

2023-09-20 03:44 UTC, merged