[XML Converter] Save Protobins within Godot
AsherGlick/Burrito pull request #265
Opened 2024-01-19 05:14 UTC by klingbolt

Replacing #159 

Changes to markers are saved in the split files. A save button takes those split files and saves them to individual files.

2024-01-19 05:48 UTC, AsherGlick requested changes
Can you split this up into 2 PRs.
* save to split proto from ingame state
* save to "export"? proto from split proto

From our previous conversation may have erroneously assumed that the former had already been completed and I think that there is going to be some discussion required on that point. While I have fewer comments about the latter.

2024-01-19 05:48 UTC, AsherGlick commented on project.godot
> +"base": "",
?

2024-01-19 05:48 UTC, AsherGlick commented on Spatial.tscn
> +visible = true
?

2024-01-19 05:48 UTC, AsherGlick commented on Spatial.tscn
> +current_path = "."
?

2024-01-19 05:48 UTC, AsherGlick commented on Spatial.tscn
> +margin_bottom = 587.0
?

2024-01-19 05:48 UTC, AsherGlick commented on Spatial.gd
> +	for waypoint_category in self.waypoint_data.get_category():
Do we need to "save" every top-level category every time the button is pressed?

2024-09-08 00:59 UTC, klingbolt commented
This PR is now obsolete and its goals covered by other PRs

2024-09-08 00:59 UTC, closed without merging